export const POST_API_SUCCESS = 'POST_API_SUCCESS';
export const POST_API_FAILURE = 'POST_API_FAILURE';
export const FETCH_POST_API = 'FETCH_POST_API';
export const LOGIN_API_START = 'LOGIN_API_START';
export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const LOGIN_API_FAILURE = 'LOGIN_API_FAILURE';